VIH-8810 - Enable private DNS requests
hmcts/vh-shared-infrastructure pull request #50
Opened 2022-07-15 15:35 UTC by chris-pateman

### JIRA link (if applicable) ###
VIH-8810

### Change description ###
Add vnet link to private DNS

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-07-19 13:01 UTC, thomaswatsonv1 approved these changes
Looks good, Chris

2022-07-21 12:04 UTC, thomaswatsonv1 submitted a review, later dismissed
Still looks good!

2022-07-21 14:45 UTC, v1ferrarij requested changes

2022-07-21 14:45 UTC, v1ferrarij commented on terraform/10-video-hearing-wowza/modules/wowza/network.tf
I would actually probably re-do this entire ruleset to be honest as its not in line with best practices.

1. I would have a rule with a of Priority 4096 which is DenyAllVnetInbound, so blocks all Vnet Traffic other than the rules with a lower priority. 
2. I would then keep Azure-LB-Probe, but add 8087 & 443 to the ports.
3. I would then amend or merge the 'REST' & 'RTMPS' rule to tighten up security, as they currently allow connection from ANY, I would only allow from specific IPs/Subnets/ServiceTags required.

2022-07-21 16:03 UTC, v1ferrarij submitted a review, later dismissed

2022-07-22 07:16 UTC, merged