VIH-9244 - Add Wowza Credentails to Dynatrace
hmcts/vh-shared-infrastructure pull request #79
Opened 2022-08-23 07:50 UTC by chris-pateman

### JIRA link (if applicable) ###
VIH-9244

### Change description ###
Add Wowza Credentails to Dynatrace

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-08-24 15:34 UTC, v1ferrarij requested changes

2022-08-24 15:34 UTC, v1ferrarij commented on azure-pipelines.wowza.yaml
> +      ref: refs/heads/VIH-9244-dynatrace-cred
needs changing

2022-08-24 15:38 UTC, chris-pateman commented on azure-pipelines.wowza.yaml
> +      ref: refs/heads/VIH-9244-dynatrace-cred
completed

2022-08-25 13:27 UTC, v1ferrarij approved these changes

2022-08-25 14:47 UTC, merged